package com.donatodev.bcm_backend.entity;

import java.time.LocalDateTime;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents a token used for verifying user registration or email confirmation.
 * <p>
 * Each token is linked to a single {@link Users} entity and has an expiration time.
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class VerificationToken {

    /**
     * Primary key of the verification token.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique token string sent to the user's email for verification.
     */
    private String token;

    /**
     * Expiration date and time of the token.
     * After this time, the token is no longer valid.
     */
    private LocalDateTime expiryDate;

    /**
     * One-to-one relationship with the associated user.
     * This field links the token to the user who needs to be verified.
     */
    @OneToOne
    @JoinColumn(name = "user_id")
    private Users user;
}
